accounts/urls.py
 
from django.urls import path
from . import views
urlpatterns = [
    path('login/', views.login_user, name="login"),
    path('register/', views.register, name="register"),
  
]

computromsocial/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
    
    path('accounts/',include('accounts.urls')),
]

posts/urls.py
from django.urls import path
from . import views
app_name = "posts"
urlpatterns=[
    path('', views.posts, name="posts"),
    path('create-post', views.create_post, name="create-posts"),
    path('edit-post/<str:pk>/', views.edit_post, name="edit-post"),
    path('delete-post/<str:pk>/', views.delete_post, name="delete-post"),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User
class Post(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts', null=True)
    likes= models.PositiveBigIntegerField(default=0,blank=True)
    created_at= models.DateField(auto_now_add=True)
    quote = models.TextField(null=True,blank=True)



class Comment(models.Model):
    
    user= models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', null=True)

    post= models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', null=True)
    text=models.TextField()

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse

def register(request):
    return render(request,'accounts/register.html')
    
def login_user(request):
    return render(request,'accounts/login.html')

posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post, Comment
from .form import PostForm, CommentForm
def posts(request):
    posts= Post.objects.all().order_by('-created_at')
  #  print(posts)
    return render(request,'posts/posts.html',{"posts":posts})

def create_post(request):
    form= PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST)
        
        if form.is_valid():
            post = form.save()
            return  redirect("posts:posts")

 
    return render(request, "posts/create_post.html",{"form": form}) 

def edit_post(request, pk):
    post= Post.objects.get(id=pk)
    form = PostForm(instance=post)
    if request.method == "POST":
        form =PostForm( request.POST,instance=post)
     
        if form.is_valid():
            form.save()
            return redirect("posts:posts")
    return render(request, 'posts/create_post.html', {'form': form})


def delete_post(request, pk):
    post=Post.objects.get(id=pk)
    if request.method == 'POST':
        post.delete() 
        return  redirect("posts:posts")
    return render(request, 'posts/delete_post.html', {'post': post})

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
</body>
</html>

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{%block content%}
{% include 'navbar.html'%}
<h1>registrar   </h1>
{% endblock %} 

posts/templates/posts/create_post.html
{% extends 'base.html'%}
{% block content %}
{% include 'navbar.html' %}
<div class="profile-form-container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
     <button type="submit" class="btn btn-primary mt-2">Submit</button>
    </form>

</div>

{% endblock %}

posts/templates/posts/delete_post.html
{% extends 'base.html'%}
{% block content %}
{% include 'navbar.html' %}
<div class="profile-form-container">
 <h5 class="card-title"> Delete Post?</h5>
<p class="card-text"> Deleting a post will permanently delete it from the database.</p>
<form method="POST" action="{% url 'posts:delete-post' post.pk %}">


    {% csrf_token %}
    <a class="btn btn-primary" href="{% url 'posts:posts' %}">keep Post</a>
    <button type="submit" class="btn btn-primary mt-2">Delete Post</button>
</form>
</div>

{% endblock %} 

posts/templates/posts/posts.html
{% extends 'base.html' %}
{% load static %}
    
{% block content %}
{% include 'navbar.html' %}

<div class="post-container">
    {% for post in posts %}
        <div class="post">
            <div class="post-header d-flex justify-content-between">
                <div class="d-flex">
                    <a href="#">
                        <img class="profile-pic" src="{% static 'images/default_epic.jpg' %}">
                    </a>
                    <h6 class="post-user">{{post.user.username}}</h6>
                </div>
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-h" style="color: gray;"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{% url 'posts:edit-post' post.pk %}">Edit</a>
                              <a class="dropdown-item" href="{% url 'posts:delete-post' post.pk %}">Delete</a>
                              <a class="dropdown-item" href="#">Go to post</a>
                              <a class="dropdown-item" href="#">Go to post</a>
                        </div>
                    </li>
                    
                </ul>
            </div>
            <div class="post-pic-container">
                <img class="post-pic" src="{% static 'images/mela.jpg' %}">
            </div>
            <div class="post-footer">
                <div class="likes d-flex">
                    <a href="#"><i class="far fa-heart fa-lg mr-1 mt-1" style="color: black;"></i></a>
                    <p><strong>{{post.likes}} likes</strong></p>
                </div>
                <p class="quote"><strong>{{post.user.username}}</strong> {{post.quote}}</p>
                <a href="#"><p class="test-muted">See the {{post.comments.all.count}} comments</p></a>
                <small class="test-muted">{{post.created_at|date:"M d, Y"}}</small>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>documento</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
   <script src="https://kit.fontawesome.com/1b2de11c6b.js" crossorigin="anonymous"></script>

   <link rel="stylesheet" href="{% static 'css/main.css'%}">
   </head>
<body>
    {% block content %}
    {% endblock%}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">computromsocial</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
     
        </ul>
      </div>
    </div>
  </nav>    